services:
  gateway:
    container_name: seny-gateway
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    restart: always
    networks:
      - seny-network-gateway

networks:
  seny-network-gateway:
    driver: bridge
    name: seny-network
    external: true
